Lint/Eval:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
  Exclude:
    - lib/miron/websocket_connection.rb
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 25
Style/BracesAroundHashParameters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
